name: Build Desktop App

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # ونڈوز 8 کی مطابقت کے لیے Node 18 بہتر ہے

      - name: Install Dependencies
        run: npm install # npm ci کے بجائے npm install استعمال کریں

      - name: Build EXE
        run: npx electron-builder --win nsis:ia32 --win nsis:x64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
